import type { ContainerCreateOptions } from 'dockerode';
import type { RunLimits } from './limits';

/**
 * Builds the Docker create options for one sandbox run (sandbox-isolation-spec §5).
 *
 * Everything security-relevant is a constant here. Callers supply only values that
 * are validated and clamped upstream (limits) or generated by the runner (IDs,
 * token). Nothing from a run request can add flags, mounts, env, or capabilities.
 */

export const SANDBOX_UID = 65532;
export const STD_DIR = '/opt/agora-std';
export const SCRATCH_DIR = '/scratch';

/** Code travels in env vars (no bind mounts, no stdin attach): base64 chunks under Linux's 128 KiB per-string limit. */
export const CODE_CHUNK_BYTES = 90_000;
export const MAX_CODE_CHUNKS = 4;
export const MAX_CODE_BYTES = CODE_CHUNK_BYTES * MAX_CODE_CHUNKS;

export interface ContainerSpecInput {
    runId: string;
    serverId: string;
    image: string;
    network: string;
    /** 'runsc' in production; 'runc' only in explicit insecure dev mode. */
    runtime: 'runsc' | 'runc';
    code: string;
    runToken: string;
    capUrl: string;
    limits: RunLimits;
}

export function containerName(runId: string): string {
    return `agora-run-${runId.trim().toLowerCase()}`;
}

export function chunkCode(code: string): string[] {
    const bytes = Buffer.from(code, 'utf8');
    if (bytes.length === 0) throw new Error('Code is empty');
    if (bytes.length > MAX_CODE_BYTES) throw new Error(`Code exceeds ${MAX_CODE_BYTES} bytes`);
    const chunks: string[] = [];
    for (let i = 0; i < bytes.length; i += CODE_CHUNK_BYTES) {
        chunks.push(bytes.subarray(i, i + CODE_CHUNK_BYTES).toString('base64'));
    }
    return chunks;
}

/** host:port Deno may connect to — the capability gateway and nothing else. */
export function capHostPort(capUrl: string): string {
    const url = new URL(capUrl);
    const port = url.port || (url.protocol === 'https:' ? '443' : '80');
    return `${url.hostname}:${port}`;
}

export function denoArgs(input: Pick<ContainerSpecInput, 'capUrl' | 'limits'>): string[] {
    const envNames = ['AGORA_CAP_URL', 'AGORA_RUN_TOKEN', ...Array.from({ length: MAX_CODE_CHUNKS }, (_, i) => `AGORA_CODE_${i}`)];
    // V8 heap below the cgroup limit so OOM surfaces as a catchable error, not SIGKILL
    const heapMb = Math.max(64, Math.floor(input.limits.memoryMb * 0.75));
    return [
        'run',
        '--no-prompt',
        '--no-config',
        '--no-lock',
        '--cached-only',
        '--deny-import',
        `--allow-net=${capHostPort(input.capUrl)}`,
        `--allow-env=${envNames.join(',')}`,
        `--allow-read=${SCRATCH_DIR},${STD_DIR}`,
        `--allow-write=${SCRATCH_DIR}`,
        `--v8-flags=--max-old-space-size=${heapMb}`,
        `${STD_DIR}/entry.ts`,
    ];
}

export function buildContainerSpec(input: ContainerSpecInput): ContainerCreateOptions {
    const { limits } = input;
    const env = [
        `AGORA_CAP_URL=${input.capUrl}`,
        `AGORA_RUN_TOKEN=${input.runToken}`,
        ...chunkCode(input.code).map((chunk, i) => `AGORA_CODE_${i}=${chunk}`),
        // Deno's cache/emit dir must be writable; rootfs is read-only
        'DENO_DIR=/tmp/deno',
        'NO_COLOR=1',
    ];
    const memoryBytes = limits.memoryMb * 1024 * 1024;

    return {
        name: containerName(input.runId),
        Image: input.image,
        Cmd: denoArgs(input),
        Env: env,
        User: `${SANDBOX_UID}:${SANDBOX_UID}`,
        WorkingDir: SCRATCH_DIR,
        AttachStdin: false,
        AttachStdout: false,
        AttachStderr: false,
        OpenStdin: false,
        Tty: false,
        NetworkDisabled: false,
        Labels: {
            'agora.run': input.runId.trim(),
            'agora.server': input.serverId.trim(),
            'agora.managed': 'runtime',
        },
        HostConfig: {
            Runtime: input.runtime,
            NetworkMode: input.network,
            Privileged: false,
            ReadonlyRootfs: true,
            Tmpfs: {
                [SCRATCH_DIR]: `rw,noexec,nosuid,nodev,size=${limits.scratchMb}m,mode=0700,uid=${SANDBOX_UID},gid=${SANDBOX_UID}`,
                '/tmp': `rw,noexec,nosuid,nodev,size=32m,mode=0700,uid=${SANDBOX_UID},gid=${SANDBOX_UID}`,
            },
            Binds: [],
            Mounts: [],
            CapDrop: ['ALL'],
            CapAdd: [],
            SecurityOpt: ['no-new-privileges'],
            PidsLimit: limits.pidsLimit,
            Memory: memoryBytes,
            MemorySwap: memoryBytes, // no swap
            NanoCpus: Math.round(limits.cpus * 1e9),
            Ulimits: [{ Name: 'nofile', Soft: 256, Hard: 256 }],
            // Bounded on-disk logs; the runner reads them after exit, then removes the container
            LogConfig: { Type: 'local', Config: { 'max-size': '1m', 'max-file': '1', compress: 'false' } },
            AutoRemove: false,
            RestartPolicy: { Name: 'no' },
            PortBindings: {},
            PublishAllPorts: false,
            Devices: [],
            IpcMode: 'private',
            PidMode: '',
            UsernsMode: '',
            ExtraHosts: [],
        },
    };
}
