import { describe, it, expect } from 'vitest';
import { parseTestResults, computedSummary, reportMarkdown, summaryPrompt, formatDuration, REPORT_LIMITS } from '../../sandbox/report';

/** WBS 4.1: test-result parsing and report text (sandbox/report.ts, used by agora:std). */

const JUNIT = `<?xml version="1.0" encoding="UTF-8"?>
<!-- generated by pytest -->
<testsuites name="pytest" tests="6" failures="2">
  <testsuite name="tests.test_api" tests="4" time="1.5">
    <testcase classname="tests.test_api" name="test_list" time="0.25"/>
    <testcase classname="tests.test_api" name="test_create" time="0.5">
      <failure message="assert 500 == 201">Traceback &lt;most recent&gt;
AssertionError: assert 500 == 201 &amp; more</failure>
    </testcase>
    <testcase classname="tests.test_api" name="test_skip" time="0">
      <skipped message="needs redis"/>
    </testcase>
    <testcase classname="tests.test_api" name="test_boom" time="0.75"><error message="RuntimeError"><![CDATA[x < y && boom]]></error></testcase>
  </testsuite>
  <testsuite name='tests.test_util' tests="1">
    <testcase classname="tests.test_util" name="test_ok" time="0.1"></testcase>
  </testsuite>
</testsuites>`;

const VITEST_JSON = {
    numTotalTests: 4, numPassedTests: 2, numFailedTests: 1, numPendingTests: 1, numTodoTests: 0,
    testResults: [
        {
            name: '/home/ci/app/test/unit/math.test.ts', status: 'failed', startTime: 1000, endTime: 1420,
            assertionResults: [
                { fullName: 'math adds', title: 'adds', status: 'passed', duration: 3 },
                { fullName: 'math divides', title: 'divides', status: 'failed', duration: 5, failureMessages: ['\u001b[31mAssertionError: expected 2 to be 3\u001b[39m\n    at math.test.ts:12'] },
                { fullName: 'math later', title: 'later', status: 'pending' },
            ],
        },
        {
            name: '/home/ci/app/test/unit/str.test.ts', status: 'passed', startTime: 1000, endTime: 1100,
            assertionResults: [{ fullName: 'str trims', title: 'trims', status: 'passed', duration: 1 }],
        },
    ],
};

describe('parseTestResults', () => {
    it('reads JUnit XML: suites, failures, errors, skips, entities, CDATA, durations', () => {
        const r = parseTestResults(JUNIT);
        expect(r.totals).toEqual({ passed: 2, failed: 2, skipped: 1, durationMs: 1600 });
        expect(r.suites).toEqual([
            { name: 'tests.test_api', passed: 1, failed: 2, skipped: 1, durationMs: 1500 },
            { name: 'tests.test_util', passed: 1, failed: 0, skipped: 0, durationMs: 100 },
        ]);
        expect(r.failures).toEqual([
            { name: 'test_create', suite: 'tests.test_api', message: 'assert 500 == 201\nTraceback <most recent>\nAssertionError: assert 500 == 201 & more' },
            { name: 'test_boom', suite: 'tests.test_api', message: 'RuntimeError\nx < y && boom' },
        ]);
    });

    it('groups JUnit cases by classname when there is no <testsuite>', () => {
        const r = parseTestResults('<testsuites><testcase classname="a.B" name="one"/><testcase classname="a.C" name="two"><failure/></testcase></testsuites>');
        expect(r.suites.map(s => [s.name, s.passed, s.failed])).toEqual([['a.C', 0, 1], ['a.B', 1, 0]]);
        expect(r.failures[0]).toEqual({ name: 'two', suite: 'a.C', message: 'failure' });
    });

    it('reads Vitest/Jest JSON, strips ANSI colors, shortens paths, uses reporter totals', () => {
        const r = parseTestResults(VITEST_JSON);
        expect(r.totals).toEqual({ passed: 2, failed: 1, skipped: 1, durationMs: 520 });
        expect(r.suites).toEqual([
            { name: 'test/unit/math.test.ts', passed: 1, failed: 1, skipped: 1, durationMs: 420 },
            { name: 'test/unit/str.test.ts', passed: 1, failed: 0, skipped: 0, durationMs: 100 },
        ]);
        expect(r.failures).toEqual([{ name: 'math divides', suite: 'test/unit/math.test.ts', message: 'AssertionError: expected 2 to be 3\n    at math.test.ts:12' }]);
        // Also accepted as a JSON string
        expect(parseTestResults(JSON.stringify(VITEST_JSON))).toEqual(r);
    });

    it('counts a test file that failed to load as a failure', () => {
        const r = parseTestResults({
            numTotalTests: 0, numPassedTests: 0, numFailedTests: 0, numPendingTests: 0,
            testResults: [{ name: 'test/broken.test.ts', status: 'failed', message: 'SyntaxError: Unexpected token', assertionResults: [] }],
        });
        expect(r.totals.failed).toBe(1);
        expect(r.failures).toEqual([{ name: 'test/broken.test.ts (failed to run)', suite: 'test/broken.test.ts', message: 'SyntaxError: Unexpected token' }]);
    });

    it('accepts Agora\'s own shape and derives totals from suites when missing', () => {
        const r = parseTestResults({ suites: [{ name: 'a', passed: 3, failed: 0, skipped: 1 }, { name: 'b', passed: 1, failed: 2, skipped: 0, durationMs: 50 }] });
        expect(r.totals).toEqual({ passed: 4, failed: 2, skipped: 1, durationMs: 50 });
        expect(r.suites[0].name).toBe('b'); // failing suites first
        expect(parseTestResults({ totals: { passed: 5, failed: -1, skipped: 'x' } }).totals).toEqual({ passed: 5, failed: 0, skipped: 0 });
    });

    it('rejects unknown input with a readable message', () => {
        for (const bad of ['not results', 42, null, { hello: 1 }]) {
            expect(() => parseTestResults(bad), String(bad)).toThrow('JUnit XML, Vitest/Jest JSON');
        }
    });

    it('clips long names and messages to the gateway limits', () => {
        const r = parseTestResults({ totals: { passed: 0, failed: 1, skipped: 0 }, failures: [{ name: 'n'.repeat(900), message: 'm'.repeat(5000) }] });
        expect(r.failures[0].name).toHaveLength(REPORT_LIMITS.failureName);
        expect(r.failures[0].message).toHaveLength(REPORT_LIMITS.failureMessage);
        expect(r.failures[0].message.endsWith('…')).toBe(true);
    });
});

describe('report text', () => {
    const r = parseTestResults(JUNIT);

    it('computed summary states counts and failing suites', () => {
        expect(computedSummary(r)).toBe('2 of 5 tests passed, 2 failed, 1 skipped in 1.6 s. Failures are in tests.test_api.');
        expect(computedSummary(parseTestResults({ totals: { passed: 0, failed: 0, skipped: 0 } }))).toBe('No tests ran.');
    });

    it('summary prompt carries the facts and forbids guessing', () => {
        const prompt = summaryPrompt(r, 'CI #7');
        expect(prompt).toContain('"CI #7"');
        expect(prompt).toContain('do not guess causes');
        expect(prompt).toContain('tests.test_api › test_create');
        expect(prompt).toContain('assert 500 == 201');
    });

    it('markdown report has status, suite table (pipes escaped), and every failure', () => {
        const md = reportMarkdown(parseTestResults({
            totals: { passed: 1, failed: 1, skipped: 0 },
            suites: [{ name: 'a|b', passed: 1, failed: 1, skipped: 0 }],
            failures: [{ name: 'breaks', suite: 'a|b', message: 'has ``` fences' }],
        }), 'Nightly', 'One failure.');
        expect(md).toContain('# Nightly');
        expect(md).toContain('**FAILED**: 1 passed · 1 failed · 0 skipped · 2 total (50% pass)');
        expect(md).toContain('| a\\|b | 1 | 1 | 0 |  |');
        expect(md).toContain('### a|b › breaks');
        expect(md).toContain("has ''' fences");
    });

    it('formats durations', () => {
        expect(formatDuration(undefined)).toBe('');
        expect(formatDuration(250)).toBe('250 ms');
        expect(formatDuration(1500)).toBe('1.5 s');
        expect(formatDuration(125_000)).toBe('2 min 5 s');
    });
});
